language: node_js

node_js:
  - '0.10'
  - '0.8'

sudo: false

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - npm install -g codeclimate-test-reporter
  - cat coverage/lcov.info | codeclimate

addons:
  code_climate:
    repo_token: xxx
